server:
  port: 9080

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false #关闭自我保护机制

spring:
  application:
    name: shop-eurka
  freemarker:
    prefer-file-system-access: false
  sleuth:
      web:
        client:
          enabled: true
      sampler:
        probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
      base-url: http://localhost:9411/ # 指定了 Zipkin 服务器的地址




