server:
  port: 9082
spring:
  profiles:
    active: dev
  application:
    name: shop-consumer-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9080/eureka/

  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 10




