spring:
  rabbitmq:
    host: 192.168.10.30
    username: guest     #默认是guest
    password: guest  #默认是guest
    virtual-host: / #默认是/
    port: 5672
    connection-timeout: 15000s



server:
  port: 8990


