server:
  port: 9084

spring:
  profiles:
    active: dev
  application:
    name: shop-user-gateway
  freemarker:
    prefer-file-system-access: false
  sleuth:
      web:
        client:
          enabled: true
      sampler:
        probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
      base-url: http://localhost:9411/ # 指定了 Zipkin 服务器的地址


eureka:
  client:
    service-url:
      defaultZone: http://localhost:9080/eureka/

#单实例路由
zuul:
  ignoredServices: '*'
  routes:
    shop-gateway:
      path: /testGateway/**
      serviceId: shop-feign-server







